### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by XVincentX** [isteven/angular-omni-bar#3]
Would be possible to publish this package as npm package as well?

**Comment by isteven** [comment]
Hi @XVincentX , 

I am currently abroad, won't have access to my dev PC for the next few days. Will try to do so when I'm back. Cheers.

**Comment by XVincentX** [comment]
Graet, looking forward to see the changes.
Please note that introducing your lib as a npm package, you should handle both case (being required by someone and being just loaded as a `<script>` file)
Have a nice day!

**Comment by isteven** [comment]
Btw I don't have experience working on NPM. Perhaps you can provide some help here?

**Comment by XVincentX** [comment]
@isteven 
Basically the thing would be to simply create a package.json file in your repository using `npm init` command and filling it appropriately.

Keep in mind that in npm you cannot rely on global objects (such as angular), bur require them ´var angular = require('angular')´.

You can see https://github.com/petejohanson/angular-hy-res as a working example.

**Comment by isteven** [comment]
@XVincentX 

Wait.. something like this? 

https://github.com/isteven/angular-multi-select/blob/master/package.json

**Comment by XVincentX** [comment]
@isteven Basically yes.
The only thing that here would not work is that your javascript file is relying on global angular object, which is not available at all. `var angular = require('angular')`
